### PR TITLE
Delete playground

### PR DESCRIPTION
**Pull request by gonzalonunez**
We learned from [iOS Folks](https://iosdevelopers.slack.com/archives/C035W33LP/p1651071235083139?thread_ts=1650991845.901989&cid=C035W33LP) that this what is killing Xcode's performance, and it seems to be true for Primer. Merging and maintaining a fork until it gets deleted in the official repo.

### CODE REVIEW

**Comment by gonzalonunez** [comment]
Sorry! This was supposed to be a PR on my own fork.

**Comment by mbrandonw** [comment]
No worries, but FWIW we are down to delete the playground (#46) from this library since it is causing so many problems.

**Comment by mbrandonw** [comment]
We just cut a release for this so you should just be able to update SPM packages to pull it in.

**Comment by gonzalonunez** [comment]
Wow — thanks Brandon!

**Pull request closed without merging**
