### PR TITLE
Show label for visited items

### PR DESCRIPTION
**Pull request by brentleyjones**

### CODE REVIEW

**Comment by brentleyjones** [comment]
Friendly ping @stephencelis @mbrandonw

**Comment by mbrandonw** [comment]
Hi @brentleyjones, do you have any info on what motivated this change and how it changes the output of `customDump`? It doesn't seem to affect the output of any our tests, so we're having a hard time understanding.

**Comment by brentleyjones** [comment]
Yes. Before this change, when dumping a class that has a property on an object, and then one of its properties also has a property on the same object, currently the output won't show the property name for the "skipped: (already visited) property.

**Comment by mbrandonw** [comment]
@brentleyjones Would it be possible to write a test case that shows this behavior?

**Comment by brentleyjones** [comment]
Will do!

**Comment by brentleyjones** [comment]
Test added. I fails without the changes in the PR.

**Comment by brentleyjones** [comment]
@mbrandonw

**Review by stephencelis — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
