### PR TITLE
fix: Resolve Xcode 13 project startup beachball due to this playground

### PR DESCRIPTION
**Pull request by importRyan**
## Motivation
Our company's app is based on TCA with lots of SPM targets. When opening our app's Xcode project, the IDE will beachball for 5-10 seconds while on the "Packages. Finishing..." stage. We've experienced this hang across several Xcode versions, including 13.3.1 (13E500a).

## Fix
After deleting or hiding this repo's playground, Xcode no longer hangs on startup while parsing SPM packages. This is similar to behavior [reported in Swift.org forums](https://forums.swift.org/t/xcode-13-3-freezes-with-spm-at-stage-packages-finishing/56456).

This PR moves the playground to a hidden directory and adds the playground to a workspace so it remains functional.

### CODE REVIEW

**Comment by stephencelis** [comment]
@importRyan Xcode has a bug where workspaces aren't saved in "recent files" when they live in an SPM package. You can even see this in the TCA repo. TCA's workspace has a lot of demo apps, though, so we kind of deal with the bug, but I'm not sure it's worth the headache in Custom Dump.

Instead, I think we should probably just delete the playground entirely, instead of trying to preserve it via a workspace? Wanna update the PR to do that?

**Comment by importRyan** [comment]
@stephencelis So sad. Deleted.

**Comment by mbrandonw** [comment]
@importRyan Thanks!

**Comment by ZevEisenberg** [comment]
The hero we deserve

**Pull request merged**
